config/routes.rb
Subs::Application.routes.draw do
 
  resources :movies

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
    
  
  resources :softs

  resources :supports, :only => [:new, :create]
  

  get "tracks/index"
 match 'clear'=>'tracks#clear'
  get "home/about"
 match 'about' => 'home#about'
  get "home/index"
  match 'contact' => 'home#contact'
  match 'results' =>'caps#results'
  match 'softs_create'=>'softs#create'
  match 'softs_correct'=>'softs#correct'
  match 'verbs' =>'verbs#verbs'
  match 'verb_one'=>'verbs#verb_one'
  match 'tenses'=>'verbs#tenses'
  match 'cap'=>'caps#cap'
  match 'ratings'=>'ratings#rating'
  match 'home' =>'home#index'

  resources :roots

  resources :ratings
  resources :verbs
  resources :home
  resources :caps do
    member do

      get 'hide'
      get 'hide_all'
    end
  end
resources :searches

    root :to => "home#index"

  end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :rate
  belongs_to :rateable, :polymorphic => true
  
  validates_uniqueness_of :user_id, :scope => [:rateable_id, :rateable_type]
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def rating
    @cap = Cap.find_by_id(params[:cap_id])
    ip = request.env['HTTP_X_REAL_IP'] || request.env['REMOTE_ADDR']
    print "#{ip} sssss\n"
    if  @cap.rate_it(params[:rating][@cap.id.to_s], ip) then
      @succeed=true
    else
      @succeed=false;
    end
    @h_ratings=Hash.new()
    h_rates  =Hash.new()

    Rate.find(:all).each do |r|
      h_rates[r.id]=r.score
    end

    Rating.find(:all,:conditions=>["user_id = ?",ip]).each do |r|
      @h_ratings[r.rateable_id]=h_rates[r.rate_id]
    end

    if @h_ratings[@cap.id] then
      @rate_default= @h_ratings[@cap.id]
    else
      @rate_default=3
    end
    
  end


end

app/helpers/ratings_helper.rb
module RatingsHelper
  def star_button(f, cap, value, checked)
     radio_button_tag("rating[#{cap.id}]", value, checked, :class => 'star')
   end
   
 
end

app/views/ratings/_rating.html.erb
    <%#= javascript_include_tag  "jquery.ui.stars.js"%>
<div id="<%=@cap.id%>_rating_div" style="display:inline;">
		<%rated_number= @rate_default || 0%>

<div id="rate_container"  style="display:inline;">
	<h5 style="display:inline;">Please click if audio is bad.</h5>

<% form_tag ratings_path,:name=>"rating_form",:id=>'rating_form', :style=>"display:inline;",:onClick=>"document.getElementById('#{@cap.id}_rating_button').click();",:method=>:get, :remote=>true do |f|%>
    <% 1.upto(1) do |value| %>
  <%= star_button f, @cap, value, (value==rated_number) %>
    <% end %>


	<!-- <input class="star" id="rating_<%=@cap.id%>_1" name="rating[<%=@cap.id%>]" type="radio" title="throw me out!" value="1">
	<input class="star" id="rating_<%=@cap.id%>_2" name="rating[<%=@cap.id%>]" type="radio" title="unclear but still useful" value="2">
	<input class="star" id="rating_<%=@cap.id%>_3" name="rating[<%=@cap.id%>]" type="radio" title="I'm good" value="3">
	<input class="star" id="rating_<%=@cap.id%>_4" name="rating[<%=@cap.id%>]" type="radio" title="I'm clear and awesome!" value="4"> -->

    <%= hidden_field_tag("cap_id", @cap.id) %>
	<%= submit_tag "Search", :id=>"#{@cap.id}_rating_button",:name => 'rating_button',:style=>"display:none;" %>
  <% end %>
  <!-- Rating: <%#= @cap.average_rating %> -->
</div end="rate_container"></div end="<%=@cap.id%>_rating_div">

app/views/ratings/rating.js.erb
$("#<%=@cap.id%>_rating_div").html("<%= escape_javascript(render(:partial => 'rating',:object=>@cap))%>");