config/routes.rb
Subs::Application.routes.draw do
 
  resources :movies

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
    
  
  resources :softs

  resources :supports, :only => [:new, :create]
  

  get "tracks/index"
 match 'clear'=>'tracks#clear'
  get "home/about"
 match 'about' => 'home#about'
  get "home/index"
  match 'contact' => 'home#contact'
  match 'results' =>'caps#results'
  match 'softs_create'=>'softs#create'
  match 'softs_correct'=>'softs#correct'
  match 'verbs' =>'verbs#verbs'
  match 'verb_one'=>'verbs#verb_one'
  match 'tenses'=>'verbs#tenses'
  match 'cap'=>'caps#cap'
  match 'ratings'=>'ratings#rating'
  match 'home' =>'home#index'

  resources :roots

  resources :ratings
  resources :verbs
  resources :home
  resources :caps do
    member do

      get 'hide'
      get 'hide_all'
    end
  end
resources :searches

    root :to => "home#index"

  end

app/models/cap.rb
#encoding: utf-8
# == Schema Information
# Schema version: 20110522210205
#
# Table name: caps
#
#  id         :integer(4)      not null, primary key
#  num        :integer(4)
#  spa        :string(255)
#  eng        :string(255)
#  por        :string(255)
#  rus        :string(255)
#  man        :string(255)
#  fre        :string(255)
#  start      :string(255)
#  stop       :string(255)
#  url        :string(255)
#  lang       :string(255)
#  source     :string(255)
#  source2    :string(255)
#  wcount     :integer(4)
#  ccount     :integer(4)
#  created_at :datetime
#  updated_at :datetime
#

class Cap < ActiveRecord::Base
  acts_as_rateable

def self.trash()
  string  = "este"
  string = string.gsub(/e/,"\(e|é\)") if string
  return string
end

def self.return_movie(movie,page)
    Search.create(:search=>movie,:page=> page)
    paginate :per_page=>4, :page=>page,
    :conditions => ["source2 = ?","#{movie.downcase}"]
end




def self.search(search,page,language)
  if connection().to_s.match(/mysql/i) then
    Search.create(:search=>search, :lang=>language, :page=> page)
    paginate :per_page=>4, :page=>page,
#    :conditions => [language + ' REGEXP ? and eng != ? and spa != ? and hide is not TRUE and spa!=eng', "(^#{search}.?| #{search}[,\.\!\?\-]?$| #{search}[,\.\!\?]? )", "",""],
    :conditions => [language + ' REGEXP ? COLLATE UTF8_GENERAL_CI and eng != ? and spa != ? and hide is not TRUE and spa!=eng ', "[[:<:]]#{search}[[:>:]]", "",""],

    :order  => 'wcount'
  else
    Search.create(:search=>search, :lang=>language, :page=> page)
     paginate :per_page=>4, :page=>page,
       :conditions => ['(lower('+language + ') similar to lower(?) or lower('+language+') similar to lower(?) or lower('+language + ') similar to lower(?)) and hide != ? and eng != ? and spa!=eng',"% #{search}(,|\.|\!|\?|\s+)%","%^#{search}(,|\.|\!|\?|\s+)%","% #{search}$%","1",""],
#       :conditions => [''+language + ' like ? and eng != ? and spa!=eng',"%#{search}%","1"],

      :order  => 'wcount'

    end
  end
end
#:conditions => [language + ' like ? and eng != ? and spa != ?', "%#{search}%", "",""],

app/controllers/caps_controller.rb
class CapsController < ApplicationController
  # GET /caps
  # GET /caps.xml


  def index
#    @caps = Cap.all
 
    @choice= params[:language]
    lang=params[:language] || "Spa"
    
    if params[:search] then
    @caps = Cap.search(params[:search], params[:page],lang)
    returned_results = @caps.size || 0

    grab_ip_info(params[:search],returned_results,params[:page],lang)
    (@verbs,@hash_id,@english) = Verb.return_verbs(@caps)

  end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @caps }
    end
  end
  
    def results
    
      if params[:movie]  then
        @caps=Cap.return_movie(params[:movie],params[:page])
   
        grab_ip_info(params[:movie],0,0,"")
      else
        @choice= params[:language]
        lang=params[:language] || "Spa"

      if ENV['RAILS_ENV']=="production" then
        if Rails.cache.exist?("#{params[:search]}-#{params[:page]}") then
           @caps = Rails.cache.read("#{params[:search]}-#{params[:page]}")
        else
          @caps = Cap.search(params[:search], params[:page],lang) 
          Rails.cache.fetch("#{params[:search]}-#{params[:page]}", :expires_in => 2.minutes){@caps}
        end
      else
          @caps = Cap.search(params[:search], params[:page],lang) 
      end
     returned_results = @caps.size || 0
     grab_ip_info(params[:search],returned_results,params[:page],lang)
    end
 
      (@verbs,@hash_id,@english) = Verb.return_verbs(@caps)



    end

    def soft()
      
    end

    def cap()
      ip = request.env['HTTP_X_REAL_IP'] || request.env['REMOTE_ADDR']
      if params[:direction]=="back" then
        @cap = Cap.find(:last,:conditions=>["url=? and num < ?", params[:url], params[:num]], :order=>'num' )
      else
        @cap = Cap.find(:first,:conditions=>["url=? and num > ?", params[:url], params[:num]], :order=>'num' )
      end
        @cap = Cap.find(:first,:conditions=>["url=? and num = ?", params[:url], params[:num]] ) if !@cap
        @cap? returned_results=1 : returned_results=0

        grab_ip_info("#{params[:num]}-#{params[:url]}",returned_results,0,"")
      caps=Array.new()
      caps<<@cap
      (@verbs,@hash_id,@english) = Verb.return_verbs(caps)
      @cap
    end

  # GET /caps/1
  # GET /caps/1.xml
  def show
    @cap = Cap.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cap }
    end
  end

  # GET /caps/new
  # GET /caps/new.xml
  def new
    @cap = Cap.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cap }
    end
  end

  # GET /caps/1/edit
  def edit
    @cap = Cap.find(params[:id])
  end

  # POST /caps
  # POST /caps.xml
  def create
    @cap = Cap.new(params[:cap])

    respond_to do |format|
      if @cap.save
        format.html { redirect_to(@cap, :notice => 'Cap was successfully created.') }
        format.xml  { render :xml => @cap, :status => :created, :location => @cap }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cap.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /caps/1
  # PUT /caps/1.xml
  def update
    @cap = Cap.find(params[:id])

    respond_to do |format|
      if @cap.update_attributes(params[:cap])
        format.html { redirect_to(@cap, :notice => 'Cap was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cap.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /caps/1
  # DELETE /caps/1.xml
  def destroy
    @cap = Cap.find(params[:id])
    @cap.destroy

    respond_to do |format|
      format.html { redirect_to(caps_url) }
      format.xml  { head :ok }
    end
  end


   def hide_all
     Rails.cache.clear()
     @cap = Cap.find(params[:id])
     @caps = Cap.find(:all, :conditions => ["url=?", @cap.url])
     @caps.each do |c|
       c.hide=1
       c.save
     end

  #render :text=>string
  #   Cap.destroy_all(:url => @cap.url)
     respond_to do |format|
       format.html { redirect_to(caps_url) }
       format.xml  { head :ok }
     end
    end


  def hide
    Rails.cache.clear()
    @cap = Cap.find(params[:id])
    @cap.hide=1
    @cap.save

 #render :text=>string
 #   Cap.destroy_all(:url => @cap.url)
    respond_to do |format|
      format.html { redirect_to(caps_url) }
      format.xml  { head :ok }
    end
   end
end

app/helpers/caps_helper.rb
module CapsHelper

end

app/views/caps/_edit.erb
<%= render 'form' %>

app/views/caps/_form.html.erb
<%= form_for(@cap) do |f| %>
  <% if @cap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cap.errors.count, "error") %> prohibited this cap from being saved:</h2>

      <ul>
      <% @cap.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :spa %><br />
    <%= f.text_field :spa %>
  </div>
  <div class="field">
    <%= f.label :eng %><br />
    <%= f.text_field :eng %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/caps/_results.html.erb
 <%= javascript_include_tag "pagination.js" %>
<div style="display:none;" onClick="javascript:localStorage.clear();">clear</div>
<div style="display:none;" onClick="javascript:alert(localStorage.getItem('history'));">show</div>

<%if @caps%>

<div id="search" >

<script>

$(document).ready(function(){
		$("#go_back").click(function(event){
			var history = localStorage.getItem('history').split("^");
			var current= history.pop();
			var forward = localStorage.getItem('forward').split("^");
			localStorage.setItem('forward',"^"+current+forward);

			if(history.length>0){
				document.getElementById('go_back').setAttribute('style',"cursor:pointer;display:inline;")
				var last_search = history[history.length-1].split("::");
				localStorage.setItem('forward',"^"+last_search+forward);

				var lang=last_search[0];
				var search=last_search[1];
				if(search){
					document.getElementById('search').value= search;
					document.getElementById('language').value= lang;
					document.getElementById('results_button').click();
//					history.shift();
//					alert(history);
					localStorage.setItem('history',history.join("^"));
					
				}else{
					document.getElementById('go_back').setAttribute('style',"cursor:pointer;display:none;")
				}
			}
			

	//		var journey = localStorage.setItem('journey',journey +"^"+lang+"::"+search);
	  	});

var scrollTop = document.body.scrollTop || document.documentElement.scrollTop;

//document.getElementById('footer').setAttribute("style","position:absolute;top:"+document.body.scrollHeight+"px");
});



	mood= new Array();
	mood["Subjuntivo"]="Used to express everything except certainty and objectivity.";
	mood["Indicativo"]="The verb mood used in ordinary, typical speech when making statements.";
	mood["Condicional"]="The verb mood used in ordinary, typical speech when making statements.";
	mood["Imperitivo"]="imperitive";


	tense= new Array();
	tense["futuro simple"] ="future."
	tense["futuro perfecto"] ="vvvvThe future perfect is formed by combining the auxiliary verb 'haber' with the past participle. habré, habrás, habrá, habremos, habréis, habrán. (yo) Habré escrito el libro antes del año nuevo. I will have written the book before the new year. "
	tense["imperfecto"]="The imperfect tense is used to refer to actions in the past that occurred repeatedly.";
	tense["pluscuamperfecto"] = "The Spanish pluperfect (aka past perfect) is used to indicate an action in the past that occurred before another action in the past. The latter can be either mentioned in the same sentence or implied. Ya había salido (cuando tú llamaste). I had already left (when you called)."
	tense["presente"]="Present";
	tense["preterito perfecto"] = "The Spanish present perfect is used just like its English counterpart: to express that something has happened at some point before now, at an unspecified time in the past.";
    tense["condicional simple"]="1. To express a wish/courtesy:<p>	Me gustaría comprar una camisa (I´d like to buy a shirt).<br>¿Podrías decirme....? (Could you tell me...?)<p>2. To express a possibility:<br>Compraríamos la motocicleta si tuviéramos* más dinero. (We would buy the motorbike if we had more money).<p>3. To give an advice:<br>¡Deberías comer más! (You should eat more!)"
	tense_type=new Array();
	tense["Tiempos compuestos"]="Present";
	tense["Tiempos simples"] = ""


	function return_mood(div,arg){
		div.title=mood[arg];
	}
	function return_tense(div,arg){
		div.title=tense[arg];
	}

	function return_tense_type(div,arg){
		div.title=tense_type[arg];

	}


	function go_to(id,num,url,direction,div){

	// alert(div.parentNode.id);	

		document.getElementById('direction').value=direction;
		document.getElementById('url').value=url;
		document.getElementById('num').value=num;
		document.getElementById('id').value=div.parentNode.id;
//		document.getElementById('cap_button').focus();
		document.getElementById('cap_button').click();
	}
	function darken(id){

	  if(document.getElementById(id)){
		document.getElementById(id).style.display='none';	

	  }		
	}
	function light_up(id,div){
	  if(document.getElementById(id)){
		var pos = getPos(div);

var scrollTop = document.body.scrollTop || document.documentElement.scrollTop;
		document.getElementById(id).style.display='inline';	
	    document.getElementById(id).style.left=(pos[0]+(document.getElementById(id+'_basic').offsetWidth*.1)) +"px";
	    document.getElementById(id).style.top=(pos[1]+document.getElementById(id+'_basic').offsetHeight-scrollTop) +"px";

	  }
	}

	function soft_edit(id,div,lang){
		if(div.innerHTML.match(/edit/)){
			div.innerHTML="save";
			document.getElementById(id+"_"+lang).style.visibility="visible";
			document.getElementById(id+"_"+lang).setAttribute("contentEditable","true");
			document.getElementById(id+"_"+lang).focus();
			document.getElementById(id+"_cancel_"+lang).style.display="inline";
			
			
		}else{
			var answer = confirm("Are you sure you want to save?")
			if (answer){
				document.getElementById('soft_text').value= document.getElementById(id+"_"+lang).innerHTML;
		    	document.getElementById('soft_id').value = id;
		    	document.getElementById('soft_lang').value = lang;
			//	document.getElementById('soft_button').focus();
				document.getElementById('soft_button').click();
				if (lang.match(/eng/i)){
					document.getElementById(id+"_edit_"+lang).innerHTML="edit English";
				}else{
					document.getElementById(id+"_"+lang).style.visibility="hidden";				
					document.getElementById(id+"_edit_"+lang).innerHTML="edit Spanish";
				}
			}else{
				soft_cancel(id,lang);	
				
			}

		
		}
	}
	
	

	
	
	function soft_cancel_wait(id,lang){
		setTimeout("soft_cancel('"+id+"','"+lang+"');",500);
	}

	
	function soft_cancel(id,lang){
		document.getElementById(id+"_eng").setAttribute("contentEditable","false");
		document.getElementById(id+"_cancel_"+lang).style.display="none";

		if (lang.match(/eng/i)){
	
			document.getElementById(id+"_edit_"+lang).innerHTML="edit English";
		}else{
			document.getElementById(id+"_"+lang).style.visibility="hidden";				
			document.getElementById(id+"_edit_"+lang).innerHTML="edit Spanish";
		}
	}

function go_to_page(){
	document.getElementById('page').value=document.getElementById('go_to').value;
	document.getElementById('movie_button').click();   
}

</script>
<% form_tag softs_create_path,:name=>"soft_form",:id=>'soft_form', :method=>:get, :format=>'js', :remote=>true do%>
<%= hidden_field_tag :soft_text, params[:soft_text] %>
<%= hidden_field_tag :soft_id, params[:soft_id] %>
<%= hidden_field_tag :soft_lang, params[:soft_lang] %>
<%= submit_tag "soft", :id=>"soft_button",:name => 'soft_button',:style=>"display:none;" %>

<%end%>
<% c=0 %>

<div id ="go_back" style="display:inline;cursor:pointer;">go back</div end="go_back">
<div id="will_paginate1">
	
	<%if params[:movie] then%>
	<button onClick="go_to_page();">go to page</button>	<input id="go_to" type="text" size='1' value='1'> 
		<%end%>

	<%= will_paginate @caps, :remote=>true %>  
	<%#= page_entries_info @caps %> 

	<% @caps.each do |cap| %>
		<%c=c+1%>
		<div id="container_<%=c%>" >
		<%= render :partial => "caps/cap", :object => cap  %>
	</div end="container_<%=c%>">
	<br><br>
	<% end %>
</div end="will_paginate1">
<br>

<div id="will_paginate2" style="position:relative;">
<%= will_paginate @caps, :remote=>true %>
<%= page_entries_info @caps %> 
<%#= link_to 'New Cap', new_cap_path %>
</div end="will_paginate2">
</div end="search">	
<%end%>

app/views/caps/cap.js.erb
var id=document.getElementById('id').value;

$('#'+id).html("<%= escape_javascript(render(:partial => 'cap'))%>");

app/views/caps/edit.html.erb
<h1>Editing cap</h1>

<%= render 'form' %>

<%#= link_to 'Show', @cap %> 
<%#= link_to 'Back', caps_path %>

app/views/caps/index.html.erb
<div id="search" style="display:inline;">

<%if !params[:hide_search] then%>

<h1>Listing captions</h1>
<% form_tag caps_path, :method=> 'get' do %>
	<p>
		<%= select_tag "language", options_for_select([ "Spa", "Eng"], @choice) %>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :name=>nil %>
	</p>
<%end%>
</div end="search">
<%end%>
<script>
	mood= new Array();
	mood["Subjuntivo"]="Used to express everything except certainty and objectivity.";
	mood["Indicativo"]="The verb mood used in ordinary, typical speech when making statements.";
	mood["Condicional"]="The verb mood used in ordinary, typical speech when making statements.";
	mood["Imperitivo"]="imperitive";


	tense= new Array();
	tense["futuro simple"] ="future."
	tense["futuro perfecto"] ="The future perfect is formed by combining the auxiliary verb 'haber' with the past participle. habré, habrás, habrá, habremos, habréis, habrán. (yo) Habré escrito el libro antes del año nuevo. I will have written the book before the new year. "
	tense["imperfecto"]="The imperfect tense is used to refer to actions in the past that occurred repeatedly.";
	tense["pluscuamperfecto"] = "The Spanish pluperfect (aka past perfect) is used to indicate an action in the past that occurred before another action in the past. The latter can be either mentioned in the same sentence or implied. Ya había salido (cuando tú llamaste). I had already left (when you called)."
	tense["presente"]="Present";
	tense["preterito perfecto"] = "The Spanish present perfect is used just like its English counterpart: to express that something has happened at some point before now, at an unspecified time in the past.";
    tense["condicional simple"]="1. To express a wish/courtesy:<p>	Me gustaría comprar una camisa (I´d like to buy a shirt).<br>¿Podrías decirme....? (Could you tell me...?)<p>2. To express a possibility:<br>Compraríamos la motocicleta si tuviéramos* más dinero. (We would buy the motorbike if we had more money).<p>3. To give an advice:<br>¡Deberías comer más! (You should eat more!)"

	tense_type=new Array();
	tense["Tiempos compuestos"]="Present";
	tense["Tiempos simples"] = ""


	function return_mood(div,arg){
		div.title=mood[arg];
	}
	function return_tense(div,arg){
		div.title=tense[arg];
	}

	function return_tense_type(div,arg){
		div.title=tense_type[arg];

	}




	function darken(id){

	  if(document.getElementById(id)){
		document.getElementById(id).style.display='none';	

	  }		
	}
	function light_up(id,div){
		alert('find me');
	  if(document.getElementById(id)){

		var pos = getPos(div);
		document.getElementById(id).style.display='inline';	
	    document.getElementById(id).style.left=(pos[0]+(document.getElementById(id+'_basic').offsetWidth*.6)) +"px";
	    document.getElementById(id).style.top=(pos[1]+document.getElementById(id+'_basic').offsetHeight) +"px";

	  }
	}





</script>

<%# @verbs.each do |v|%>
	<%#= v %>
	<%#end%>
	<%if @caps%>
<table>
  <tr>
<!--
	<th>Id</th>
    

<th>Num</th>
-->
	<th></th>
    <th>Spanish</th>
    <th>English</th>
<!--
    <th>Por</th>
    <th>Rus</th>
    <th>Man</th>
    <th>Fre</th>

    <th>Start</th>
    <th>Stop</th>
   
--> 
<th></th>
<th></th>

	<!--
<th>Url</th>
    <th>Lang</th>
    <th>Wcount</th>
    <th>Ccount</th>

    <th></th>
    <th></th>
    <th></th>
-->
   <th></th>
  </tr>
<% c=0 %>

<% @caps.each do |cap|  %>
<%c=c+1%>
  <tr>
<!--
	<td><%= cap.id %></td>

-->
<!--	<td><audio src="http://www.mikefab.com/mp3/2641baee-e0ad-4eee-a0ce-cb4696a2b84e/05_2641baee-e0ad-4eee-a0ce-cb4696a2b84e.mp3" controls preload="auto" autobuffer></audio></td>
   <td><%= cap.num %></td>
-->

	<td>
		<%# if FileTest.exists?(RAILS_ROOT + "/public/audio/spa/#{cap.url}/#{cap.num}_#{cap.url}.mp3")==true%> 
		<%# if FileTest.exists?("http://www.mikefab.com/spa/#{cap.url}/#{cap.num}_#{cap.url}.mp3")==true%> 
		<% if cap.source == "dotsub" %> 
		<audio src="http://www.mikefab.com/ogg/spa/<%=cap.url%>/<%= cap.num %>_<%= cap.url %>.ogg" controls preload="auto" autobuffer></audio>
		<%else%>
			<%cap.source2=cap.source2.gsub(" ",".")%>
			<audio src="http://www.mikefab.com/ogg/spa/movies/<%=cap.source2%>/<%= cap.num %>_<%= cap.source2  %>.ogg" controls preload="auto" autobuffer></audio>
		<%end%>

		<!-- <audio id="player<%=c%>" src="/ogg/spa/<%=cap.url%>/<%= cap.num %>_<%= cap.url %>.ogg" onClick="#document.getElementById('player<%=c%>').src='/ogg/spa/<%=cap.url%>/<%= cap.num %>_<%= cap.url %>.ogg';" controls preload="auto" onClick="alert('hi')";loop="loop"></audio> -->
		<!-- <button onClick="document.getElementById('player<%=c%>').src='/audio/spa/<%=cap.url%>/<%= cap.num %>_<%= cap.url %>.mp3';document.getElementById('player<%=c%>').play();"> Listen  </button> -->
<!---->
	<%# end %>	
	</td>

	<%counter=0%>
    <td><%cap.spa.split(/\s+/).each do |w|%>
<%thing="#{cap.id}-#{counter}"%>
	<span id="<%=cap.id%>-<%=counter%>_basic" onmouseover="light_up('<%=cap.id%>-<%=counter%>',this);" onmouseout="darken('<%=cap.id%>-<%=counter%>');">
	<a href='/caps?utf8=%E2%9C%93&language=Spa&search=<%=w%>'><%=w%>
</a></span>
<%if @hash_id[thing] then%>
	<!-- title="<%= @hash_id[thing].conj%> : <%= @hash_id[thing].verb%> <%=@hash_id[thing].tense%>"> -->
	<span id="<%=cap.id%>-<%=counter%>" style="position:fixed;z-index:3;background-color:yellow;display:none;" onmouseover="this.style.display='inline';" onmouseout="this.style.display='none';">
	<%= @hash_id[thing].conj%>
	<br>verb: <a href=""><%= @hash_id[thing].verb%> - <%=@english["#{@hash_id[thing].verb}"]%></a>
	<br>tense:<a href=""        onmouseover="return_tense(this,'<%=@hash_id[thing].tense%>');"><%=@hash_id[thing].tense%></a>
	<br>mood:  <a href=""       onmouseover="return_mood(this,'<%=@hash_id[thing].mood%>');"><%=@hash_id[thing].mood%></a>

	<br>tense type:  <a href="" onmouseover="return_tense_type(this,'<%=@hash_id[thing].tense_type%>');"><%=@hash_id[thing].tense_type%></a>
	<br>pronoun: <a href=""> <%=@hash_id[thing].pro%></a>
	
	</span>
 	<%end%>

	<%counter=counter+1%>

	<%end%></td>

    <td><%= cap.eng %></td>
<!--
    <td><%= cap.por %></td>
    <td><%= cap.rus %></td>
    <td><%= cap.man %></td>
    <td><%= cap.fre %></td>

    <td><%= cap.start %></td>
    <td><%= cap.stop %></td>

-->

<!--
<td><%= cap.url %></td>    
    <td><%= cap.lang %></td>
    <td><%= cap.wcount %></td>
    <td><%= cap.ccount %></td>

    <td><%= link_to 'Show', cap %></td>
    <td><%= link_to 'Edit', edit_cap_path(cap) %></td>
    <td><%= link_to 'Destroy', cap, :confirm => 'Are you sure?', :method => :delete %></td>

-->

    <td style="width:60px;font-size:8pt;" title="Removes just this file."><%= link_to 'remove',hide_cap_path(cap), :confirm => 'Are you sure?' %></td>
    <td style="width:100px;font-size:8pt;" title="Removes all clips in database from same video"><%= link_to 'remove all', hide_all_cap_path(cap), :confirm => 'Are you sure?'  %></td>

  </tr>
<% end %>
</table>
<br />
<%= will_paginate @caps %>
<%= page_entries_info @caps %> 
<%#= link_to 'New Cap', new_cap_path %>
<%end%>

app/views/caps/new.html.erb
<h1>New cap</h1>

<%= render 'form' %>

<%= link_to 'Back', caps_path %>

app/views/caps/results.js.erb
$("#results_div").html("<%= escape_javascript(render(:partial => 'results'))%>");

app/views/caps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Num:</b>
  <%= @cap.num %>
</p>

<p>
  <b>Spa:</b>
  <%= @cap.spa %>
</p>

<p>
  <b>Eng:</b>
  <%= @cap.eng %>
</p>

<p>
  <b>Por:</b>
  <%= @cap.por %>
</p>

<p>
  <b>Rus:</b>
  <%= @cap.rus %>
</p>

<p>
  <b>Man:</b>
  <%= @cap.man %>
</p>

<p>
  <b>Fre:</b>
  <%= @cap.fre %>
</p>

<p>
  <b>Start:</b>
  <%= @cap.start %>
</p>

<p>
  <b>Stop:</b>
  <%= @cap.stop %>
</p>

<p>
  <b>Url:</b>
  <%= @cap.url %>
</p>

<p>
  <b>Lang:</b>
  <%= @cap.lang %>
</p>

<p>
  <b>Wcount:</b>
  <%= @cap.wcount %>
</p>

<p>
  <b>Ccount:</b>
  <%= @cap.ccount %>
</p>


<%= link_to 'Edit', edit_cap_path(@cap) %> |
<%= link_to 'Back', caps_path %>