config/routes.rb
Subs::Application.routes.draw do
 
  resources :movies

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
    
  
  resources :softs

  resources :supports, :only => [:new, :create]
  

  get "tracks/index"
 match 'clear'=>'tracks#clear'
  get "home/about"
 match 'about' => 'home#about'
  get "home/index"
  match 'contact' => 'home#contact'
  match 'results' =>'caps#results'
  match 'softs_create'=>'softs#create'
  match 'softs_correct'=>'softs#correct'
  match 'verbs' =>'verbs#verbs'
  match 'verb_one'=>'verbs#verb_one'
  match 'tenses'=>'verbs#tenses'
  match 'cap'=>'caps#cap'
  match 'ratings'=>'ratings#rating'
  match 'home' =>'home#index'

  resources :roots

  resources :ratings
  resources :verbs
  resources :home
  resources :caps do
    member do

      get 'hide'
      get 'hide_all'
    end
  end
resources :searches

    root :to => "home#index"

  end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # GET /searches
  # GET /searches.xml
  def index
    @searches = Search.all(:order=>"created_at")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @searches }
    end
  end

  # GET /searches/1
  # GET /searches/1.xml
  def show
    @search = Search.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @search }
    end
  end

  # GET /searches/new
  # GET /searches/new.xml
  def new
    @search = Search.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @search }
    end
  end

  # GET /searches/1/edit
  def edit
    @search = Search.find(params[:id])
  end

  # POST /searches
  # POST /searches.xml
  def create
    @search = Search.new(params[:search])

    respond_to do |format|
      if @search.save
        format.html { redirect_to(@search, :notice => 'Search was successfully created.') }
        format.xml  { render :xml => @search, :status => :created, :location => @search }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /searches/1
  # PUT /searches/1.xml
  def update
    @search = Search.find(params[:id])

    respond_to do |format|
      if @search.update_attributes(params[:search])
        format.html { redirect_to(@search, :notice => 'Search was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.xml
  def destroy
    @search = Search.find(params[:id])
    @search.destroy

    respond_to do |format|
      format.html { redirect_to(searches_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :search %><br />
    <%= f.text_field :search %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :lang %><br />
    <%= f.text_field :lang %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :page %><br />
    <%= f.text_field :page %>
  </div>
  <div class="field">
    <%= f.label :option %><br />
    <%= f.check_box :option %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<h1>Listing searches</h1>

<table>
  <tr>
    <th>Search</th>
    <th>User</th>
    <th>Lang</th>
    <th>Category</th>
    <th>Page</th>
    <th>Option</th>
	<th>Created</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @searches.each do |search| %>
  <tr>
    <td><%= search.search %></td>
    <td><%= search.user_id %></td>
    <td><%= search.lang %></td>
    <td><%= search.category %></td>
    <td><%= search.page %></td>
    <td><%= search.option %></td>
    <td><%= search.created_at %></td>
    <td><%= link_to 'Show', search %></td>
    <td><%= link_to 'Edit', edit_search_path(search) %></td>
    <td><%= link_to 'Destroy', search, :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Search:</b>
  <%= @search.search %>
</p>

<p>
  <b>User:</b>
  <%= @search.user_id %>
</p>

<p>
  <b>Lang:</b>
  <%= @search.lang %>
</p>

<p>
  <b>Category:</b>
  <%= @search.category %>
</p>

<p>
  <b>Page:</b>
  <%= @search.page %>
</p>

<p>
  <b>Option:</b>
  <%= @search.option %>
</p>


<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>