config/routes.rb
Subs::Application.routes.draw do
 
  resources :movies

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
    
  
  resources :softs

  resources :supports, :only => [:new, :create]
  

  get "tracks/index"
 match 'clear'=>'tracks#clear'
  get "home/about"
 match 'about' => 'home#about'
  get "home/index"
  match 'contact' => 'home#contact'
  match 'results' =>'caps#results'
  match 'softs_create'=>'softs#create'
  match 'softs_correct'=>'softs#correct'
  match 'verbs' =>'verbs#verbs'
  match 'verb_one'=>'verbs#verb_one'
  match 'tenses'=>'verbs#tenses'
  match 'cap'=>'caps#cap'
  match 'ratings'=>'ratings#rating'
  match 'home' =>'home#index'

  resources :roots

  resources :ratings
  resources :verbs
  resources :home
  resources :caps do
    member do

      get 'hide'
      get 'hide_all'
    end
  end
resources :searches

    root :to => "home#index"

  end

app/models/verb.rb
# coding: utf-8
class Verb < ActiveRecord::Base

def self.all_cached

#  Rails.cache.fetch('Verb.all') { all }
end

  def self.num_verbs()
    v = Verb.find(:all)
    return v.size
  end
  
  def self.return_verb(verb)
    verb_hash=Hash.new()
    Verb.find(:all,:conditions=>["verb=?",verb]).each do |v|
      verb_hash[v.conj]=1 if Word.find(:first,:conditions=>["word=?",v.conj])
    end
    return verb_hash
      
  end

  def self.return_tenses(mood)

    if Rails.cache.read("#{mood}") 
      return Rails.cache.read("#{mood}").split(/:/) if Rails.cache.read("#{mood}") 
    else
#      tenses = ["futuro perfecto", "futuro simple", "gerundio", "imperfecto", "infinitivo", "participio", "pluscuamperfecto", "presente", "pretérito perfecto","pretérito anterior","condicional simple","condicional perfecto"]
      tenses = ["presente", "imperfecto", "pretérito perfecto", "pretérito anterior", "pluscuamperfecto", "futuro simple", "futuro perfecto", "infinitivo","gerundio","condicional simple","condicional perfecto","participio"]
      a=Array.new()
      tenses.each do |t|
        v= Verb.find(:first, :conditions=>["mood = ? and tense = ?", "#{mood}","#{t}"])
        a<<t if v
      end
      
      a_string=a.join(":")
#      Rails.cache.write("#{mood}","#{a_string}")
      Rails.cache.fetch("#{mood}", :expires_in =>3.days){"#{a_string}"}

      return a
    end
  end

  def self.return_mood_verbs(mood,tense)
    if Rails.cache.read("#{mood}#{tense}") 
      return Rails.cache.read("#{mood}#{tense}") 
    else
    a_verbs=Array.new()
    a_strings=Array.new()
    hash_words=Hash.new()
    grand_verb=Hash.new() #for all matching conjugations through life of function
    small_verb=Hash.new() #for unique conjugations with matching words.
    conjugations=ActiveRecord::Migration.execute("select conj,verb from verbs where mood = '#{mood}' and tense = '#{tense}';")


    if connection().to_s.match(/mysql/i) then
      conjugations.each do |j|
       a_strings<<j[0]
        grand_verb[j[0]]=j[1]
      end
    else
      #mu'fuck'n po'gres
      conj_count=ActiveRecord::Migration.execute("select count(*) from verbs where mood = '#{mood}' and tense = '#{tense}';")
     conj_count[0]["count"].to_i.times{|i| a_strings<< conjugations[i]['conj']}
     conj_count[0]["count"].to_i.times{|i| grand_verb[conjugations[i]['conj']]=conjugations[i]['verb']}

    end
     words=ActiveRecord::Migration.execute("select word from words;")
     if connection().to_s.match(/mysql/i) then
       words.each do |w|
         hash_words[w[0]]=1
       end
     else
       word_count=ActiveRecord::Migration.execute("select count(*) from words;")
       word_count[0]["count"].to_i.times{|i| hash_words[words[i]['word']]=1 }
     end
     
    #Many conjugations repeat, so make list unique
    a_strings=a_strings.uniq
    #Now find out if each conjugation is found in a caption
    a_strings.each do |s|

      if hash_words[s]
#        a_strings << s
        small_verb[s]=grand_verb[s]
      end
    end
#    Rails.cache.write("#{mood}#{tense}",small_verb.sort)
      Rails.cache.fetch("#{mood}#{tense}", :expires_in =>3.days){small_verb.sort}
     return small_verb.sort
  end
end


  def self.return_verbs(caps)
    verbs=""
    text=""
    a_caps=[]
    hash_ids=Hash.new()
    hash_id=Hash.new()
    english=Hash.new()
    
    caps.each do |cap|
      cap.spa=cap.spa.gsub(/\s+/," ")
      text = cap.spa.split(/\s+/)
      #loop through each word
      #push each word into a_caps
      #push each word and predecessor into a_caps
      text.length.times do |i|
      text[i] = text[i].gsub(/(\?|\!|\.|,)/,"")
  
      text[i-1] = text[i-1].gsub(/(\?|\!|\.|,)/,"")if i>0
        text[i].downcase!
        a_caps.push(text[i])
        a_caps.push("#{text[i-1]} #{text[i]}") if i>0
        
        #Create hash with words as keys and the value a string of all its positions in captions (id-i)
        if hash_ids["#{text[i]}"] then
          hash_ids["#{text[i]}"] = hash_ids["#{text[i]}"] + "#{cap.id}-#{i}|"
        else
             hash_ids["#{text[i]}"] ="#{cap.id}-#{i}|"
        end

         if hash_ids["#{text[i-1]} #{text[i]}"]  then
          hash_ids["#{text[i-1]} #{text[i]}"] = hash_ids["#{text[i-1]} #{text[i]}"] +  "#{cap.id}-#{i}|"
         else
           hash_ids["#{text[i-1]} #{text[i]}"] = "#{cap.id}-#{i}|"
         end
      end
    end
    a_caps.uniq!
    a_caps.each do |word|

      #remove punctuation from word or compound before checking if it's a verb
      word = word.gsub(/(\?|\!|\.|,)/,"")

 if ENV['RAILS_ENV']=="production" then
      if Rails.cache.read("conj-#{word}") then 
        temp = Rails.cache.read("conj-#{word}")
      else
        temp = Verb.find(:first,:conditions=>['conj = ?',"#{word}"])
        Rails.cache.fetch("conj-#{word}", :expires_in => 3.days){temp}
      end
    else
      temp = Verb.find(:first,:conditions=>['conj = ?',"#{word}"])
  end


      #loop through ids for each word, initialize hash set id as key and verb as value
      if hash_ids[word] and temp then
        #get english translation for verb
        #trans=Root.find(:first,:conditions=>['verb=?',temp.verb])
#          english["#{temp.verb}"]=trans.trans
          english[temp.verb]=Rails.cache.read("hash_trans")[temp.verb]
        hash_ids[word] =  hash_ids[word].sub(/|$/,"")
        array_of_ids = hash_ids[word].split("|")
        array_of_ids.each do |id|

        hash_id["#{id}"] = temp
  #      puts "#{hash_id[id].verb} #{id}"
      end
    end
    verbs = verbs + " | " + word + " - " + temp.verb if temp
    end
  [verbs,hash_id,english]
  end



end

app/controllers/verbs_controller.rb
class VerbsController < ApplicationController
  # GET /verbs
  # GET /verbs.xml
  def index

    @verbs = Verb.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @verbs }
    end
  end

  def tenses


    @tenses = Verb.return_tenses(params[:tense_mood])
    returned_results=@tenses.size || 0
    grab_ip_info(params[:tense_mood], returned_results,0,"")
  end

  def verbs

    if(params[:verb].size>0)
      @verbs = Verb.return_verb(params[:verb])
    else
      @verbs = Verb.return_mood_verbs(params[:verb_mood],params[:verb_tense])
    end

   end
    
    
  # GET /verbs/1
  # GET /verbs/1.xml
  def show
    @verb = Verb.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @verb }
    end
  end

  # GET /verbs/new
  # GET /verbs/new.xml
  def new
    @verb = Verb.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @verb }
    end
  end

  # GET /verbs/1/edit
  def edit
    @verb = Verb.find(params[:id])
  end

  # POST /verbs
  # POST /verbs.xml
  def create
    @verb = Verb.new(params[:verb])

    respond_to do |format|
      if @verb.save
        format.html { redirect_to(@verb, :notice => 'Verb was successfully created.') }
        format.xml  { render :xml => @verb, :status => :created, :location => @verb }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @verb.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /verbs/1
  # PUT /verbs/1.xml
  def update
    @verb = Verb.find(params[:id])

    respond_to do |format|
      if @verb.update_attributes(params[:verb])
        format.html { redirect_to(@verb, :notice => 'Verb was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @verb.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /verbs/1
  # DELETE /verbs/1.xml
  def destroy
    @verb = Verb.find(params[:id])
    @verb.destroy

    respond_to do |format|
      format.html { redirect_to(verbs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/verbs_helper.rb
module VerbsHelper
end

app/views/verbs/_form.html.erb
<%= form_for(@verb) do |f| %>
  <% if @verb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@verb.errors.count, "error") %> prohibited this verb from being saved:</h2>

      <ul>
      <% @verb.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :verb %><br />
    <%= f.text_field :verb %>
  </div>
  <div class="field">
    <%= f.label :conj %><br />
    <%= f.text_field :conj %>
  </div>
  <div class="field">
    <%= f.label :mood %><br />
    <%= f.text_field :mood %>
  </div>
  <div class="field">
    <%= f.label :tense %><br />
    <%= f.text_field :tense %>
  </div>
  <div class="field">
    <%= f.label :tense_type %><br />
    <%= f.text_field :tense_type %>
  </div>
  <div class="field">
    <%= f.label :pro %><br />
    <%= f.text_field :pro %>
  </div>
  <div class="field">
    <%= f.label :pre %><br />
    <%= f.text_field :pre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/verbs/_tenses.html.erb
<script>

    $(function(){
		// for(i=0;i<10;i++){
		//                $("#instruction2").animate({color: "blue"}, 'slow');
		//                $("#instruction2").animate({color: "red"}, 'slow');
		// 	}
    });


tense_width=new Array();
tense_width["future perfecto"] ="10";
tense_width["futuro simple"] ="20";
tense_width["imperfecto"] ="50";
tense_width["pluscuamperfecto"] ="30";
tense_width["futuro simple"] ="20";
tense_width["pretérito perfecto"] ="30";
tense_width["presente"] ="20";
tense_width["pretérito anterior"]="30"



tense_main= new Array();
tense_main["participio"]="The participle which, in both<br>Spanish and English, can be used <br>as an adjective or with<br> auxiliary verbs to form<br> the perfect tenses or the passive voice.<br>Examples:<br>I have studied in Barcelona.<br>(He estudiado en Barcelona.)<br><br> My friend was arrested.<br> (Mi amiga fue detenida.)<br><br>I had eaten the burnt potatoes.<br> (Había comido las papas quemadas.)"
tense_main["infinitivo"]="The infinitive is the basic,<br>unconjugated form of a verb,<br>sometimes called the name of the verb.<br>In English the infinitive is<br>to + verb: to talk, to eat,<br> to leave, etc.<br>Infinitivos have one of the following endings:<br> -ar, -er, or -ir"
tense_main["gerundio"]="a special, invariable form of the verb which<br>always ends in -ndo in Spanish,<br>for example: hablando, comiendo, viviendo.<br>In English it is translated as the '-ing'<br> form of the verb (for example, 'speaking')";
tense_main["condicional simple"]="1. To express a wish/courtesy:<p>	Me gustaría comprar una camisa (I´d like to buy a shirt).<br>¿Podrías decirme....? (Could you tell me...?)<p>2. To express a possibility:<br>Compraríamos la motocicleta si tuviéramos* más dinero. (We would buy the motorbike if we had more money).<p>3. To give an advice:<br>¡Deberías comer más! (You should eat more!)"
tense_main["condicional perfecto"]="The conditional perfect is used to make statements that are contrary to reality.<br> Something would, or would not, have happened if some condition had been met.<p>As an example,<br>'I would have done the assingment last night, if I had only taken my notebook with me to the party'.<p>The conditional perfect can also be used to express probability or<br>conjecture about the completion of an action prior to some point in the past:<p>El habría sacado la gorda antes de comprar aquella mansion.<br>He would have won the lottery before purchasing that mansion.<p>El profesor le habría prometido una marca perfecta cuando empezó el curso.<br>The professor must have promised him an A plus when he started the course."
tense_main["futuro simple"] ="future."
tense_main["futuro perfecto"] ="The future perfect is formed by combining<br>the auxiliary verb 'haber' with the past participle.<br>habré, habrás, habrá, habremos, habréis, habrán."+
"<p> (yo) Habré escrito el libro antes del año nuevo."+
"<br> I will have written the book before the new year. "+
"<p>(tú) ¿Habrás comprado una casa en un año?"+
"<br>Will you have bought a house in a year?"+

"<p>(él) Habrá pagado todas las deudas para el<br> dos de octubre."+
"<br>He will have paid all the debt by October 2."+

"<p>(nosotros) Habremos vuelto de España para<br>el doce de junio."+
"<br>We will have returned from Spain by June 12."+

"<p>(vosotros) Para cuando Juan llegue, vosotros ya habréis salido."+
"<br>By the time Juan arrives, you-all will already have left."+

"<p>(ellos) Para cuando María vuelva, ellos ya habrán comido."+
"<br>By the time Maria returns, they will have already eaten.";

tense_main["imperfecto"]="The imperfect tense is used to refer to actions in the past that occurred repeatedly."+
"<p>The imperfect is used for actions that were repeated habitually."+
"<p>Almorzábamos juntos todos los días."+
"<br>We would lunch together every day."+

"<p>Las señoras siempre charlaban por las mañanas."+
"<br>The ladies would always chat in the mornings."+

"<p>The imperfect is used for actions that 'set the stage' for another action."+
"<br>Yo leía cuando entró mi papá."+
"<br>I was reading when my papa entered."+

"<p>The imperfect is used for telling time and stating one's age."+
"<br>Eran las siete de la noche."+
"<br>It was seven o'clock at night."+

"<p>La niña tenía cinco años."+
"<br>The little girl was five years old.";


tense_main["pluscuamperfecto"] = "The Spanish pluperfect (aka past perfect) is used to indicate an action in the past that occurred before another action in the past. The latter can be either mentioned in the same sentence or implied. Ya había salido (cuando tú llamaste). I had already left (when you called)."
tense_main["presente"]="Present";
tense_main["pretérito perfecto"] = "The Spanish present perfect is used just like its English counterpart: to express that something has happened at some point before now, at an unspecified time in the past.";
tense_main["pretérito anterior"]="We use the Pretérito Anterior of the Indicative Mood when talking about the past and we want to mention that a past action happened 'immediately' before another past action In the modern spoken language this tense is practically never used.<br><br>To form the Pretérito Anterior of the Indicative Mood, you take the auxiliary verb 'haber' (to have) conjugated in the Pretérito perfecto simple or pretérito indefinido of the indicative mood (per person) and then add the past participle of another verb."


// function getPos(el) {
//     // yay readability
//     for (var lx=0, ly=0;
//          el != null;
//          lx += el.offsetLeft, ly += el.offsetTop, el = el.offsetParent);
// //    return {x: lx,y: ly};
// 	return[lx,ly];
// //alert(lx,ly);
// }
function explain_tense(div){
	var pos = getPos(div);
	document.getElementById('tense_explanation').innerHTML= tense_main[div.innerHTML];
	var height=div.offsetHeight + 5;
	var left = pos[0]-9;
	document.getElementById('tense_explanation').setAttribute('style','position:relative;z-index:1;left:'+left+'px;top:'+height+'px;width:'+tense_width[div.innerHTML]+'%;background-color:yellow;border: 3px black solid;')

}
function off_tense_explanation(){
	document.getElementById('tense_explanation').setAttribute('style',"position:relative;display:none;")
}

function highlight_tense(div){

//	document.getElementById('mood_explination').innerHTML=mood_des[div.innerHTML];
	child_divs = document.getElementById("tenses_holder").childNodes;
	for(var i = 0; i < child_divs.length; i++){
	 if (child_divs[i].nodeType==1){child_divs[i].style.color="black";}
	}
	div.style.color="blue";
	// document.getElementById('tense_mood').value=div.innerHTML;
	// document.getElementById('verb_mood').value=div.innerHTML;
	// 
	// document.getElementById('mood_button').focus();
	// document.getElementById('mood_button').click();
}



</script>
<div id="tenses"  style="position:absolute;top:-20px">
<%if @tenses%>	

<div id="tenses_holder" style="position:relative;display:inline;left:-70px;">
	<%c=1%>
	<%@tenses.each do |t| %>
	<div class="tenses" id="<%=c%>_tense" style="position:relative;display:inline;cursor:pointer;" onClick="document.getElementById('verb').value='';document.getElementById('instruction2').style.visibility='hidden';display_verbs(this.innerHTML);highlight_tense(this);" onmouseover= "explain_tense(this);" onmouseout="off_tense_explanation();"><%=t%></div end="<%=c%>_tense">
	<%c=c+1%>
	<%end%>

</div end="tenses_holder">
<%end%>

<div id="tense_explanation" style="position:relative;width:200px;"></div end="tense_explanation">
<div id="tense_example" style="position:relative;width:200px;"></div end="tense_example">
</div end="tenses">

app/views/verbs/_verbs.html.erb
<script>
    $(function(){

// 		for(i=0;i<5;i++){
//                $("#instruction3").animate({color: "red"}, 'slow');
//                $("#instruction3").animate({color: "blue"}, 'slow');
// }
    });

</script>

<%@verbs = eval(@verbs) if @verbs.class.to_s.match("String")%>
<%if @verbs%>

	<%c=0%>
	<%if @verbs.size==0 then%>
<div id="empty_verb_warning" style="position:relative">	There are no verbs for this tense yet.<br>
		Please click another tense.</div end="empty_verb_warning">
	<%else%>
	<div id="instruction3" style="color:red;">Now, click a verb below<br>to see it in action!
	</div end="instruction3">
	<div id="verb_place">
		<%@verbs.each do |k,v| %>
			<%c=c+1%>
	<div id="verb_container">
	<div id="<%=c%>_verb" title="<%=v%>-<%=Rails.cache.read("hash_trans")[v]%>"style="cursor:pointer;display:inline;" onClick="display_results(this.innerHTML);" ><%=k%></div end="<%=c%>_verb">
	</div end="verb_container">	

	<%end%>
</div end="verb_place">
	<%end%>
<%end%>

app/views/verbs/edit.html.erb
<h1>Editing verb</h1>

<%= render 'form' %>

<%= link_to 'Show', @verb %> |
<%= link_to 'Back', verbs_path %>

app/views/verbs/index.html.erb
<h1>Listing verbs</h1>

<table>
  <tr>
    <th>Verb</th>
    <th>Conj</th>
    <th>Mood</th>
    <th>Tense</th>
    <th>Tense type</th>
    <th>Pro</th>
    <th>Pre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @verbs.each do |verb| %>
  <tr>
    <td><%= verb.verb %></td>
    <td><%= verb.conj %></td>
    <td><%= verb.mood %></td>
    <td><%= verb.tense %></td>
    <td><%= verb.tense_type %></td>
    <td><%= verb.pro %></td>
    <td><%= verb.pre %></td>
    <td><%= link_to 'Show', verb %></td>
    <td><%= link_to 'Edit', edit_verb_path(verb) %></td>
    <td><%= link_to 'Destroy', verb, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Verb', new_verb_path %>

app/views/verbs/new.html.erb
<h1>New verb</h1>

<%= render 'form' %>

<%= link_to 'Back', verbs_path %>

app/views/verbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Verb:</b>
  <%= @verb.verb %>
</p>

<p>
  <b>Conj:</b>
  <%= @verb.conj %>
</p>

<p>
  <b>Mood:</b>
  <%= @verb.mood %>
</p>

<p>
  <b>Tense:</b>
  <%= @verb.tense %>
</p>

<p>
  <b>Tense type:</b>
  <%= @verb.tense_type %>
</p>

<p>
  <b>Pro:</b>
  <%= @verb.pro %>
</p>

<p>
  <b>Pre:</b>
  <%= @verb.pre %>
</p>


<%= link_to 'Edit', edit_verb_path(@verb) %> |
<%= link_to 'Back', verbs_path %>

app/views/verbs/tenses.html.erb
<script>
function display_verbs(value){
	parent.document.getElementById('verbs').src="/verbs?mood="+parent.mood+ "&tense="+value;

}
</script>
<div style="position:absolute;top:-20px">
<table cellpadding="100px">
	<tr >
<%@tenses.each do |t| %>

<td><h4 onClick="display_verbs(this.innerHTML);"><%=t%></h4></td>
<%end%>
</tr></table>
</div>

app/views/verbs/tenses.js.erb
$("#tenses_div").html("<%= escape_javascript(render(:partial => 'tenses'))%>");

$(function (){  
//		document.getElementById('instruction2').style.visibility='hidden';
		var first_tense= document.getElementById('1_tense');
		if (!first_tense.innerHTML.match(/futuro perfecto/)){
			display_verbs(first_tense.innerHTML);
			highlight_tense(first_tense);
			refresh_tenses=0;
		}else{
			var first_tense= document.getElementById('2_tense');
			display_verbs(first_tense.innerHTML);
			highlight_tense(first_tense);
			refresh_tenses=0;
			
		}

});

app/views/verbs/verbs.js.erb
$("#verbs_div").html("<%=escape_javascript(render(:partial => 'verbs'))%>");
$(function (){  
display_results(document.getElementById('1_verb').innerHTML);
//   setTimeout("document.getElementById('1_verb').focus();document.getElementById('1_verb').click();",1000);  

});